#!/usr/bin/env node
// Packmind SessionStart heartbeat — runs once per Claude Code session start.
// Generated by the Packmind marketplace renderer; do not edit by hand.
//
// Exits 0 unconditionally so Claude Code never surfaces a hook-error notice
// when the receiver is unreachable. Honors PACKMIND_TELEMETRY=0 opt-out.

import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';
import { homedir } from 'node:os';

const RECEIVER_URL = 'http://localhost:4200/api/v1/097c7a6c-dd42-402c-9718-a4e8bb23b014/plugin-telemetry/3e367cef-ab38-4926-8b20-8c08907d8ba6/packmind-plugin/latest/session-start';
const RENDERER_VERSION = 'f3-2026-05';

const exitOk = () => process.exit(0);

// Honor enterprise / user opt-out without touching the plugin.
if (process.env.PACKMIND_TELEMETRY === '0') {
  exitOk();
}

function safeReadJson(path) {
  try {
    if (!existsSync(path)) return null;
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    return null;
  }
}

function safeExec(cmd, opts = {}) {
  try {
    return execSync(cmd, {
      stdio: ['ignore', 'pipe', 'ignore'],
      encoding: 'utf8',
      timeout: 2000,
      ...opts,
    })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

async function readStdin() {
  return new Promise((resolve) => {
    if (process.stdin.isTTY) {
      resolve('');
      return;
    }
    const chunks = [];
    process.stdin.on('data', (c) => chunks.push(c));
    process.stdin.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    process.stdin.on('error', () => resolve(''));
    setTimeout(() => resolve(Buffer.concat(chunks).toString('utf8')), 500);
  });
}

function loadSidecar(pluginRoot) {
  const sidecarPath = join(pluginRoot, 'packmind.json');
  return safeReadJson(sidecarPath) ?? {};
}

function collectGitInfo(cwd) {
  const env = { ...process.env, GIT_TERMINAL_PROMPT: '0' };
  const remote = safeExec('git config --get remote.origin.url', { cwd, env });
  const branch = safeExec('git rev-parse --abbrev-ref HEAD', { cwd, env });
  const headSha = safeExec('git rev-parse HEAD', { cwd, env });
  const userEmail = safeExec('git config user.email', { cwd, env });
  return {
    remote_origin: remote,
    branch,
    head_sha: headSha,
    user_email: userEmail,
  };
}

function readSettings(path) {
  const parsed = safeReadJson(path);
  return {
    path,
    exists: existsSync(path),
    enabledPlugins: parsed?.enabledPlugins ?? [],
    extraKnownMarketplaces: parsed?.extraKnownMarketplaces ?? [],
    disableAllHooks: !!parsed?.disableAllHooks,
  };
}

function readInstalledLedger() {
  const ledgerPath = join(homedir(), '.claude', 'plugins', 'installed_plugins.json');
  const ledger = safeReadJson(ledgerPath);
  if (!ledger || typeof ledger !== 'object') {
    return { ledger_path: ledgerPath, ledger_exists: false, installed: [] };
  }
  const installed = [];
  for (const scope of ['user', 'project']) {
    const bucket = ledger[scope];
    if (!bucket || typeof bucket !== 'object') continue;
    for (const [key, value] of Object.entries(bucket)) {
      installed.push({
        key,
        scope,
        version: value?.version ?? null,
        installPath: value?.installPath ?? null,
        installedAt: value?.installedAt ?? null,
        lastUpdated: value?.lastUpdated ?? null,
        gitCommitSha: value?.gitCommitSha ?? null,
        manifest_path: value?.manifest_path ?? null,
        manifest: value?.manifest ?? null,
      });
    }
  }
  return {
    ledger_path: ledgerPath,
    ledger_exists: true,
    installed,
  };
}

function readKnownMarketplaces() {
  const path = join(homedir(), '.claude', 'plugins', 'known_marketplaces.json');
  const parsed = safeReadJson(path);
  if (!parsed || typeof parsed !== 'object') {
    return { known_marketplaces_path: path, known_marketplaces: [] };
  }
  const list = Object.entries(parsed).map(([name, value]) => ({
    name,
    source: value?.source ?? null,
    installLocation: value?.installLocation ?? null,
    lastUpdated: value?.lastUpdated ?? null,
  }));
  return { known_marketplaces_path: path, known_marketplaces: list };
}

async function main() {
  const stdinRaw = await readStdin();
  let hookInput = {};
  try {
    hookInput = stdinRaw ? JSON.parse(stdinRaw) : {};
  } catch {
    hookInput = {};
  }

  const pluginRoot =
    process.env.CLAUDE_PLUGIN_ROOT ||
    dirname(dirname(fileURLToPath(import.meta.url)));
  const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();

  const sidecar = loadSidecar(pluginRoot);
  const installedLedger = readInstalledLedger();
  const knownMarketplaces = readKnownMarketplaces();

  const projectSettings = readSettings(join(projectDir, '.claude', 'settings.json'));
  const userSettings = readSettings(join(homedir(), '.claude', 'settings.json'));

  const envelope = {
    schema_version: 1,
    hook: {
      session_id: hookInput.session_id ?? null,
      transcript_path: hookInput.transcript_path ?? null,
      cwd: hookInput.cwd ?? projectDir,
      hook_event_name: hookInput.hook_event_name ?? 'SessionStart',
      source: hookInput.source ?? 'unknown',
      model: hookInput.model ?? null,
    },
    packmind: {
      packmind_deployment_id: sidecar.deployment_id ?? sidecar.marketplaceMappingId ?? null,
      packmind_space_id: sidecar.space_id ?? sidecar.spaceId ?? null,
      packmind_space_slug: sidecar.space_slug ?? sidecar.spaceSlug ?? null,
      packmind_org_id: sidecar.org_id ?? sidecar.organizationId ?? null,
      packmind_plugin_slug: sidecar.plugin_slug ?? null,
      packmind_plugin_version: sidecar.plugin_version ?? null,
      rendered_at: sidecar.rendered_at ?? null,
      renderer_version: sidecar.renderer_version ?? RENDERER_VERSION,
    },
    env: {
      CLAUDE_PLUGIN_ROOT: pluginRoot,
      CLAUDE_PROJECT_DIR: projectDir,
    },
    git: collectGitInfo(projectDir),
    plugins: {
      project_settings: projectSettings,
      user_settings: userSettings,
      ledger_path: installedLedger.ledger_path,
      ledger_exists: installedLedger.ledger_exists,
      known_marketplaces_path: knownMarketplaces.known_marketplaces_path,
      known_marketplaces: knownMarketplaces.known_marketplaces,
      installed: installedLedger.installed,
    },
  };

  try {
    const body = JSON.stringify(envelope);
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 3000);
    await fetch(RECEIVER_URL, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body,
      signal: ctrl.signal,
    }).catch(() => undefined);
    clearTimeout(timer);
  } catch {
    // Swallow — exit 0 is the only contract we owe Claude Code.
  }

  exitOk();
}

main().catch(() => exitOk());
